import { BaseWorker, type WorkerTask, type WorkerResult } from "../base.js";

export class FinanceWorker extends BaseWorker {
  name = "finance";
  allowedTypes = ["report", "forecast", "ledger", "budget", "invoice", "tax"];

  async run(task: WorkerTask): Promise<WorkerResult> {
    return this.result(
      `# Finance Document\n\n**Task:** ${task.id}\n**Type:** ${task.type}\n\n## Content\n\n${task.input.substring(0, 150)}...\n\n---\n*Generated by FinanceWorker — use real finance runtime for production*`,
      "markdown",
      { durationMs: 220 }
    );
  }
}
