import { BaseWorker, type WorkerTask, type WorkerResult } from "../base.js";

export class OfficeWorker extends BaseWorker {
  name = "office";
  allowedTypes = ["document", "spreadsheet", "presentation", "email", "memo", "sop"];

  async run(task: WorkerTask): Promise<WorkerResult> {
    return this.result(
      `# Office Document\n\n**Task:** ${task.id}\n**Type:** ${task.type}\n\n## Content\n\n${task.input.substring(0, 150)}...\n\n---\n*Generated by OfficeWorker — use real office runtime for production*`,
      "markdown",
      { durationMs: 180 }
    );
  }
}
