import { BaseWorker, type WorkerTask, type WorkerResult } from "../base.js";

export class SalesWorker extends BaseWorker {
  name = "sales";
  allowedTypes = ["lead", "proposal", "contract", "crm", "pipeline", "quote"];

  async run(task: WorkerTask): Promise<WorkerResult> {
    return this.result(
      `# Sales Document\n\n**Task:** ${task.id}\n**Type:** ${task.type}\n\n## Content\n\n${task.input.substring(0, 150)}...\n\n---\n*Generated by SalesWorker — use real sales runtime for production*`,
      "markdown",
      { durationMs: 200 }
    );
  }
}
